[package]
name = "drogue-tls"
version = "0.1.0"
edition = "2018"
authors = [
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Ulf Lilleengen <lulf@redhat.com>"
]

[dependencies]
p256 = { version = "0.8.0-pre", default-features = false, features = [ "ecdh", "arithmetic" ] }
rand_core = { version = "0.6.2", default-features = false }
hkdf = "0.10.0"
hmac = "0.10.1"
sha2 = { version = "0.9.3", default-features = false }
aes-gcm = { version = "0.8.0", default-features = false, features = ["aes"] }
digest = { version = "0.9.0", default-features = false }
typenum = "1.13.0"
heapless = "0.6"
generic-array = "0.14"
log = "0.4"
nom = { version = "6.1.2", default-features = false }

[dev-dependencies]
env_logger = "0.8"
tokio = { version = "1.7", features = ["full"] }
rand = "0.8"

[features]
defmt-default = [ ]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
